# Generated by Django 4.1.3 on 2023-01-30 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_foodlike_food_remove_foodlike_liked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
